---
swagger: "2.0"
info:
  x-ibm-name: "firewall-test-api"
  title: "Firewall Test API"
  version: "1.0.0"
  description: "To check Firewall connectivity from DataPower to back-end"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/xml"
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
    description: "vaibhav.salunkhe@toyota.com"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "var BackendURL = apim.getvariable('message.headers.URL');\nvar ctx\
          \ = session.name('myContext') || session.createContext('myContext');\nctx.setVariable('BackendURL',\
          \ BackendURL);\napim.setvariable('BackendURL',BackendURL);\n"
    - proxy:
        title: "proxy"
        timeout: 60
        verb: "keep"
        cache-response: "protocol"
        cache-ttl: 900
        version: "1.0.0"
        target-url: "$(BackendURL)"
  phase: "realized"
paths:
  /firewalltest:
    get:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "URL"
        type: "string"
        required: true
        in: "header"
        description: "https://<hostname>:<port>"
definitions: {}
tags: []
